file_format: "1"
id: oath_pro
name: Oath Pro
type: shield
url: https://github.com/agile-fish/Oath-66-Duo
requires: [nice_nano_v2]
features:
  - keys
  - studio
  - dongle
siblings:
  - oath_pro_left
  - oath_pro_right